In [1]:
import pandas as pd

In [2]:
from pandas import Series, Dataframe

ImportError: cannot import name 'Dataframe' from 'pandas' (/opt/homebrew/Cellar/jupyterlab/3.4.3/libexec/lib/python3.10/site-packages/pandas/__init__.py)

In [3]:
obj = pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2['d'] = 6

In [13]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

NameError: name 'np' is not defined

In [17]:
import numpy as np

In [18]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b'in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000,'Texas' : 71000,'Oregon': 16000,'Utah': 5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
states = ['California','Ohio','Oregon','Texas']

In [25]:
obj4 = pd.Series(sdata,index = states)

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
obj4.name = 'population'

In [33]:
obj4.index.name = 'state'

In [34]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [36]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [38]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year': [2000,2001,2002,2001,2002,2003],
       'pop': [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.Dataframe(data)

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [39]:
import dataframe

ModuleNotFoundError: No module named 'dataframe'

In [40]:
from pandas import dataframe

ImportError: cannot import name 'dataframe' from 'pandas' (/opt/homebrew/Cellar/jupyterlab/3.4.3/libexec/lib/python3.10/site-packages/pandas/__init__.py)

In [41]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year': [2000,2001,2002,2001,2002,2003],
       'pop': [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [42]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [43]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [44]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [45]:
frame2 = pd.DataFrame(data,columns = ['year','state','pop','debt'],
                     index= ['one','two','three','four','five','six'])

In [46]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [49]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [50]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [51]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [52]:
frame2['debt'] = 16.5

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [54]:
frame2['debt']= np.arrange(6.)

AttributeError: module 'numpy' has no attribute 'arrange'

In [55]:
import numpy as np

In [56]:
frame2['debt'] = np.arrange(6.)

AttributeError: module 'numpy' has no attribute 'arrange'

In [57]:
frame2['debt'] = np.arange(6.)

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [60]:
val = pd.Series([-1.2, -1.5,-1.7], index=['two','four','five'])

In [61]:
frame2['debt'] = val

In [62]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [63]:
frame2['eastern'] = frame2.state == 'Ohio'

In [64]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [65]:
del frame2['eastern']

In [66]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [67]:
pop = {'Nevada':{2001: 2.4, 2002: 2.9},
       'Ohio' : {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [68]:
frame3 = pd.DataFrame(pop)

In [69]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [70]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [71]:
pd.DataFrame(pop, index = [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [72]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [73]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [74]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [75]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [76]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [77]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [78]:
obj = pd.Series(range(3), index=['a','b','c'])

In [79]:
index = obj.index

In [80]:
index

Index(['a', 'b', 'c'], dtype='object')

In [81]:
index[1:]

Index(['b', 'c'], dtype='object')

In [83]:
labels = pd.Index(np.arange(3))

In [84]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [85]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)

In [86]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [87]:
obj2.index is labels

True

In [88]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [90]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [91]:
'Ohio'in frame3.columns

True

In [92]:
2003 in frame3.index

False

In [94]:
dup_labels = pd.Index(['foo','foo','bar','baz'])

In [95]:
dup_labels

Index(['foo', 'foo', 'bar', 'baz'], dtype='object')

In [96]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [97]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [98]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [99]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [100]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])

In [101]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [103]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [104]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a','c','d'],
                    columns= ['Ohio','Texas','California'])

In [105]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [106]:
frame2 = frame.reindex(['a','b','c','d'])

In [107]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [110]:
states = ['Texas','Utah','California']

In [111]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [115]:
frame.loc[['a','b','c','d'],states]

KeyError: "['Utah'] not in index"

In [116]:
frame2.loc[['a','c','d'],states]

KeyError: "['Utah'] not in index"

In [117]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [118]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [119]:
new_obj = obj.drop('c')

In [120]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [121]:
obj.drop(['d','c'])


a    0.0
b    1.0
e    4.0
dtype: float64

In [133]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index= ['Ohio','Colorado','Utah','New York'],
                    columns= ['one','two','three','four'])

In [134]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [135]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [137]:
data.drop(['two','four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [138]:
obj.drop('c', inplace = True)

In [139]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [140]:
obj = pd.Series(np.arange(4.), index=['a','b','c','d'])

In [141]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [142]:
obj['b']

1.0

In [143]:
obj[1]

1.0

In [144]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [145]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [146]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [147]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [148]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [149]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [150]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [151]:
data[data['three']> 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [152]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [153]:
data[data < 5] = 0

In [154]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [155]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [156]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [157]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [159]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [160]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [161]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [167]:
ser = pd.Series(np.arange(3.))

In [168]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [164]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])

In [165]:
ser2[-1]

2.0

In [169]:
ser[:1]

0    0.0
dtype: float64

In [170]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [171]:
ser.iloc[:1]

0    0.0
dtype: float64

In [175]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a',c','d','e'])

SyntaxError: unterminated string literal (detected at line 1) (2568053200.py, line 1)

In [176]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])

In [177]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [178]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1], index=['a','c','e','f','g'])

In [179]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [180]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [183]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
                   index = ['Ohio','Texas','Colorado'])




In [186]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                   index = ['Utah','Ohio','Texas','Oregon'])

In [187]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [188]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [189]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [190]:
df1 = pd.DataFrame({'A':[1,2]})

In [191]:
df1

A
0  1
1  2

In [192]:
df2 = pd.DataFrame({'B':[3,4]})

In [193]:
df2

B
0  3
1  4

In [194]:
df1 - df2


A   B
0 NaN NaN
1 NaN NaN

In [195]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [196]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))

In [197]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [198]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns=list('abcde'))


In [199]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [200]:
df2.loc[1,'b']=np.nan

In [201]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [202]:
df1 + df2


a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [203]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [204]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [205]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [206]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [208]:
arr = np.arange(12.).reshape((3,4))

In [209]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [210]:
arr[0]

array([0., 1., 2., 3.])

In [211]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [212]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns=list('bde'),
                    index=['UTAH','OHIO','TEXAS','OREGON'])

In [213]:
frame

b     d     e
UTAH    0.0   1.0   2.0
OHIO    3.0   4.0   5.0
TEXAS   6.0   7.0   8.0
OREGON  9.0  10.0  11.0

In [214]:
series = frame.iloc[0]

In [215]:
series

b    0.0
d    1.0
e    2.0
Name: UTAH, dtype: float64

In [216]:
frame - series

b    d    e
UTAH    0.0  0.0  0.0
OHIO    3.0  3.0  3.0
TEXAS   6.0  6.0  6.0
OREGON  9.0  9.0  9.0

In [217]:
series2 = pd.Series(range(3),index=['b','e','f'])

In [218]:
series2

b    0
e    1
f    2
dtype: int64

In [219]:
frame + series

b     d     e
UTAH    0.0   2.0   4.0
OHIO    3.0   5.0   7.0
TEXAS   6.0   8.0  10.0
OREGON  9.0  11.0  13.0

In [220]:
frame + series2

b   d     e   f
UTAH    0.0 NaN   3.0 NaN
OHIO    3.0 NaN   6.0 NaN
TEXAS   6.0 NaN   9.0 NaN
OREGON  9.0 NaN  12.0 NaN

In [221]:
frame

b     d     e
UTAH    0.0   1.0   2.0
OHIO    3.0   4.0   5.0
TEXAS   6.0   7.0   8.0
OREGON  9.0  10.0  11.0

In [222]:
series3 = frame['d']

In [223]:
series3

UTAH       1.0
OHIO       4.0
TEXAS      7.0
OREGON    10.0
Name: d, dtype: float64

In [224]:
frame.sub(series3,axis='index')

b    d    e
UTAH   -1.0  0.0  1.0
OHIO   -1.0  0.0  1.0
TEXAS  -1.0  0.0  1.0
OREGON -1.0  0.0  1.0

In [226]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                     index=['Utah','Ohio','Texas','Oregon'])

In [227]:
frame

b         d         e
Utah    1.892600 -0.538928 -1.545907
Ohio    1.092312  0.765904  0.923633
Texas  -2.223278 -0.712795 -0.437031
Oregon  0.144766  0.417951 -0.308147

In [228]:
np.abs(frame)

b         d         e
Utah    1.892600  0.538928  1.545907
Ohio    1.092312  0.765904  0.923633
Texas   2.223278  0.712795  0.437031
Oregon  0.144766  0.417951  0.308147

In [229]:
f = lambda x:x.max()-x.min()

In [230]:
frame.apply(f)

b    4.115878
d    1.478699
e    2.469540
dtype: float64

In [231]:
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max'])

In [232]:
frame.apply(f)

b         d         e
min -2.223278 -0.712795 -1.545907
max  1.892600  0.765904  0.923633

In [233]:
format = lambda x: '%.2f'% x

In [234]:
frame.applymap(format)

b      d      e
Utah     1.89  -0.54  -1.55
Ohio     1.09   0.77   0.92
Texas   -2.22  -0.71  -0.44
Oregon   0.14   0.42  -0.31

In [235]:
frame['e'].map(format)

Utah      -1.55
Ohio       0.92
Texas     -0.44
Oregon    -0.31
Name: e, dtype: object

In [236]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [237]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [238]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns=['d','a','b','c'])

In [239]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [240]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [241]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [242]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [243]:
obj=pd.Series([4,7,-3,2])

In [244]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [245]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [246]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [247]:
frame= pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [248]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [249]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [250]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [254]:
obj= pd.Series([7,-5,7,4,2,0,4])

In [255]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [256]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [258]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [259]:
frame = pd.DataFrame({'b': [4.3,7,-3,2],'a':[0,1,0,1],
                     'c':[-2,5,8,-2.5]})

In [260]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [261]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [262]:
obj= pd.Series(range(5),index=['a','a','b','b','c'])

In [263]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [264]:
obj['a']

a    0
a    1
dtype: int64

In [265]:
obj['c']

4

In [266]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [267]:
df

0         1         2
a  2.685549 -0.836408 -0.399579
a -0.967250  0.979047  0.086638
b -1.550031 -0.302184 -0.245529
b -0.739262 -0.654186  0.669241

In [268]:
df.loc['b']

0         1         2
b -1.550031 -0.302184 -0.245529
b -0.739262 -0.654186  0.669241

In [274]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],
                 [np.nan,np.nan],[0.75,-1.3]],
                 index=['a','b','c','d'],
                 columns=['one','two'])

In [270]:
df

one  two
a  1.40  NaN
b  7.10  4.5
c   NaN  NaN
d  0.75 -1.3

In [275]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [276]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [277]:
df.mean(axis="columns",skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [279]:
df.idxmax()

one    b
two    d
dtype: object

In [280]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [281]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [282]:
obj = pd.Series(['a','a','b','c']*4)

In [283]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [284]:
import pandas_datareader.data as web

ModuleNotFoundError: No module named 'pandas_datareader'

In [285]:
conda install pandas_datareader

ValueError: The python kernel does not appear to be a conda environment.  Please use ``%pip install`` instead.

In [286]:
pip3 install pandas_datareader

SyntaxError: invalid syntax (2193508424.py, line 1)

In [287]:
pip install pandas_datareader

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 28.1 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
  Created wheel for lxml: filename=lxml-4.9.1-cp310-cp310-macosx_12_0_arm64.whl size=1492384 sha256=82337b0b6c273e00e43ab03c7161ac90654cc2940abe11e940c1eb6757fe0406
  Stored in directory: /Users/payel/Library/Caches/pip/wheels/a4/ec/7b/8acde6da24b5aabeee049213d5bec12d1e9214d3cae276387b
Successfully built lxml

[notice] A new release of pip available: 22.1.2 -> 22.2
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/3.4.3/libexec/bin/python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [288]:
import pandas_datareader.data as web

In [290]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in['APPL','IBM','MSFT','GOOG']}

KeyError: 'Date'